# Generated by Django 4.1.2 on 2024-04-30 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_worker', models.TextField()),
                ('born_date', models.DateField(null=True)),
                ('work_date', models.DateField(null=True)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.position')),
            ],
            options={
                'verbose_name': 'ФИО',
                'verbose_name_plural': 'ФИО',
                'ordering': ['-id'],
            },
        ),
    ]
