# Generated by Django 4.1.2 on 2024-05-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='img',
            field=models.ImageField(null='True', upload_to='img/'),
            preserve_default='True',
        ),
    ]
