 # Generated by Django 4.1.2 on 2024-05-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_worker_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='position_parent',
            field=models.IntegerField(null=True),
        ),
    ]
